# Dependencies
markdown: kramdown
highlighter: rouge

#  Build
theme: jekyll-theme-minimal
title: Repositorio SAP ABAP
description: Repositorio libre con códigos para aprender programación SAP ahora.
google_analytics: UA-102273252-1
avatar: https://avatars2.githubusercontent.com/u/23317692?v=3&u=3319301a436f2b42d9c4fa89370ddc2e40c0feea
permalink: /:categories/:title.html
baseurl: /ABAP
url: https://consultoria-sap.github.io/ABAP/
timezone: America/Argentina/Buenos_Aires
excerpt_separator: <!--more-->
gems:
  - jekyll-sitemap
  - jemoji

#repository: "consultoria-sap/ABAP"
#staticman:
#  branch: "master"

# Agrego carpetas
#defaults:
#  - scope:
#      path: "codigos"
      
# lista
#carpeta-list: [code]
